#define                 MAJOR_VERSION                   0
#define                 MINOR_VERSION                   0
#define                 PATCH_VERSION                   1

#undef                  MAX_PLAYERS
#define                 MAX_PLAYERS                     (10)
#define                 SCM                             SendClientMessage
#define                 SCMTA                           SendClientMessageToAll